package com.maruti.enums;

public enum Context {

//	userType, 
	citySelectedOnSelectCityScreen, 
	price, 
	userFKID,
	userTokenID,
	userUUID,
	selectedSubscriptionTenure, 
//	actualSubscriptionTenure,
	selectedDateOnFilterScreen,
	selectedDateInput, 
	carName, 
	effectiveMonthlyCost, 
	userMobileNo, 
	userEmailId,
	availableFromDate,
	carActualPrice,
	carDiscountedPrice,
	carMonthlyCharge, 
	vehicleDiscount,
	mailid,
	monthlyChargesStriked,
	discountedPrice,
	OTP,
	bookingID,
	firstDeliveryAddress,
	firstBillingAddress,
	noOfActiveBillingAddress,
	noOfActiveDeliveryAddress,
	updatedEmail,
	updatedMobile,
	userName,
	regEmailID, 
	regName,
	compareCarFirst,
	compareCarSecond,
	rentOutDateFrom,
	rentOutDateEnd;
}